from app.schemas.all_schemas import *

__all__ = [
    "RegisterRequest",
    "LoginRequest",
    "AuthResponse",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "ProfileBase",
    "ProfileUpdate",
    "CareerPreferencesSchema",
    "OnboardingStep1",
    "OnboardingStep2",
    "OnboardingStep3",
    "OnboardingStep4",
    "OnboardingFullRequest",
    "CandidateProfileSchema",
    "ProfileResponse",
    "ResumeResponse",
    "ATSScoreBreakdown",
    "ResumeAnalysisResponse",
    "JobSummary",
    "JobDetail",
    "ScoreBreakdown",
    "JobMatchExplanation",
    "SkillGapItem",
    "SkillGapResponse",
    "MarketTrendItem",
    "CareerInsightsResponse",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationItem",
    "NotificationItem",
    "DashboardResponse",
]
